lynx/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from todo.views import RegisterView
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('todo.urls', 'todo'), namespace='todo')),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('accounts/register/', RegisterView.as_view(), name='register'),
]

todo/urls.py
from django.urls import path
from .views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView, 
    TaskDeleteView,
    complete_task
)
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', TaskListView.as_view(), name='tasks-list'),
    path('tasks/', TaskListView.as_view(), name='tasks-list'),
    path('task/<slug:pk>', TaskDetailView.as_view(), name='task-detail'),
    path('tasks/create/', TaskCreateView.as_view(), name='task-create'),
    path('task/<slug:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('task/<slug:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),

    path('task/<slug:pk>/complete/', complete_task, name='task-complete'),

]

todo/models.py
from django.db.models import (
    Model,
    UUIDField,
    CharField,
    DateTimeField,
    TextField,
    BooleanField,
    ForeignKey,
    CASCADE,
    Index
)

from uuid import uuid4

# import user model
from django.contrib.auth import get_user_model



PRIORITY_CHOICES = (
    ('low', 'Low'),
    ('medium', 'Medium'),
    ('high', 'High'),
)

class BaseModel(Model):
    uuid = UUIDField(
        default=uuid4,
        editable=False,
        unique=True,
        db_index=True)
    created_at = DateTimeField(
        auto_now=True,
        auto_now_add=False)
    updated_at = DateTimeField(
        auto_now=True,
        auto_now_add=False)

    class Meta:
        abstract = True

class Category(BaseModel):
    name = CharField(max_length=200)
    
    def __str__(self):
        return self.name

class Task(BaseModel):
    title = CharField(max_length=200)
    description = TextField(null=True, blank=True)
    complete = BooleanField(default=False)
    due_date = DateTimeField(null=True, blank=True)
    priority = CharField(
        max_length=10,
        choices=PRIORITY_CHOICES,
        default='low')
    user = ForeignKey(
        get_user_model(),
        on_delete=CASCADE,
        default=None,
        related_name='tasks', null=True)
    category = ForeignKey(
        Category,
        on_delete=CASCADE,
        default=None,
        related_name='tasks',
        null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete'] 
        indexes = [Index(fields=['title'])]
        

todo/forms.py
from datetime import datetime
from django.forms import ModelForm, DateTimeInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Task

class TaskForm(ModelForm):
    """
    A ModelForm for creating or updating a Task instance.

    The form includes fields for the Task's title, description, due date, priority,
    and category. It also includes a widget for the due date field that displays a
    date-time picker in the browser.

    Attributes:
        Meta: A class containing metadata about the form, such as the model it
            relates to, the fields it includes, and any additional options.

    Note:
        This form assumes that the `Task` model has fields named `title`,
        `description`, `due_date`, `priority`, and `category`. It also assumes
        that the `due_date` field is a DateTimeField.
    """
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'priority', 'category']
        widgets = {
            'due_date': DateTimeInput(attrs={
                'type': 'datetime-local',
                'min': datetime.now().strftime('%Y-%m-%dT%H:%M')
            })
        }


class CustomUserCreationForm(UserCreationForm):
    """
    A form for creating a new user with customized fields and removing help texts.

    This form extends the UserCreationForm provided by Django to remove help texts 
    for the 'username', 'password1' and 'password2' fields. It allows creating 
    a new user with fields 'username', 'first_name', 'last_name', 'password1' 
    and 'password2'.

    Attributes:
    -----------
    model: Model
        The User model to create a new user from.
    fields: Tuple
        A tuple of field names to be included in the form.
    """
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs)->None:
        """
        Initialize the CustomUserCreationForm class instance.

        This method is called when the class instance is created and removes help texts 
        for the 'username', 'password1' and 'password2' fields of the form.

        Parameters:
        -----------
        *args: Any
            Variable length argument list.
        **kwargs: Any
            Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

todo/views.py
from django.views.generic import (
    View, ListView,
    DetailView, CreateView,
    UpdateView, DeleteView)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpRequest
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.http import Http404

from .models import Task
from .forms import TaskForm, CustomUserCreationForm


class BaseView(View):
    """
    Base view class for tasks-related views.

    This class provides common functionality for views that deal with tasks,
    such as retrieving a task object from the database based on a URL parameter.

    Attributes:
        None

    Methods:
        get_object: Retrieve a task object from the database based on a URL parameter.
    """

    def get_object(self, queryset=None)->Task:
        """
        Retrieve a task object from the database based on a URL parameter.

        This method retrieves a Task object from the database based on the value of
        the 'pk' URL parameter, which is expected to be a UUID. If the Task object
        is not found in the database, a Http404 exception is raised.

        Args:
            queryset (QuerySet, optional): A QuerySet of Task objects to search for
                the specified UUID. Defaults to None.

        Returns:
            Task: A Task object with the specified UUID.

        Raises:
            Http404: If no Task object with the specified UUID is found in the database.
        """
        
        return get_object_or_404(Task, uuid=self.kwargs['pk'])
    
    def dispatch(self, request, *args, **kwargs):
        """
        Override the parent class method to catch Http404 exceptions and display a custom error page.
        """
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return render(request, 'todo/404.html', {'message': 'Page not found'}, status=404)
        

class TaskDetailView(BaseView, DetailView):
    """
    Display detailed information about a single task.
    """
    model = Task


class TaskListView(LoginRequiredMixin, ListView):
    """
    Display a list of tasks.

    This view displays a list of tasks. The list is paginated to display 10 tasks per page.
    If the user is not authenticated, the list is empty.

    Attributes:
        model (Task): The Task model that this view operates on.
        ordering (str): The field to order the tasks by. Defaults to '-due_date'.
        paginate_by (int): The number of tasks to display per page. Defaults to 10.

    Methods:
        get_queryset: Retrieve a QuerySet of Task objects from the database.

    """
    model = Task
    ordering = ['-due_date']
    paginate_by = 10

    def get_queryset(self)->Task:
        """
        Retrieve a QuerySet of Task objects from the database.

        This method retrieves a QuerySet of Task objects from the database, filtered to
        include only tasks that belong to the current user (if authenticated). The list
        of tasks is sorted by due date, with the most urgent tasks displayed first.

        Returns:
            QuerySet: A QuerySet of Task objects.

        """
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            queryset = queryset.filter(user=user)
        else:
            queryset = queryset.none()
        return queryset


class TaskCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    """
    Create a new task.

    Attributes:
        model (Task): The Task model that this view operates on.
        form_class (TaskForm): The form used to create a new task.
        success_message (str): The message to display on successful task creation.

    Methods:
        get_success_url: Get the URL to redirect to after successful form submission.
        form_valid: Handle a valid form submission.
    """

    model = Task
    form_class = TaskForm
    success_message = "Task created_at successfully"

    def get_success_url(self)->str:
        """
        Get the URL to redirect to after successful form submission.

        Returns:
            str: The URL to redirect to.
        """
        return reverse_lazy('todo:task-detail', kwargs={'pk': self.object.uuid})
    
    def form_valid(self, form:TaskForm)->HttpResponse:
        """
        Handle a valid form submission.

        This method is called when a valid form is submitted. It creates a new task
        object and sets the task's user attribute to the current user.

        Args:
            form (TaskForm): The form object containing the user's input.

        Returns:
            HttpResponse: The response object.
        """
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, BaseView, UpdateView):
    """
    TaskUpdateView allows authenticated users to update an existing task.

    Attributes:
        model (Task): The Task model that this view operates on.
        form_class (TaskForm): The form used to update a task.
        success_message (str): The message to display on successful task update.

    Methods:
        get_success_url: Get the URL to redirect to after successful form submission.

    """
    model = Task
    form_class = TaskForm
    success_message = "Task updated successfully"
    
    def get_success_url(self)->str:
        """
        Get the URL to redirect to after successful form submission.

        Returns:
            str: The URL to redirect to.

        """
        return reverse_lazy('todo:task-detail', kwargs={'pk': self.object.uuid})


class TaskDeleteView(LoginRequiredMixin, BaseView, DeleteView):
    """
    TaskDeleteView allows authenticated users to delete an existing task.

    Attributes:
        model (Task): The model class used by the view to retrieve the task object.
        success_message (str): The message to display on successful deletion of a task.
        success_url (str): The URL to redirect to on successful deletion of a task.
    """
    model = Task
    success_message = "Task deleted successfully"
    success_url = reverse_lazy('todo:tasks-list')


class RegisterView(CreateView):
    """
    A view that allows a user to register for an account.

    The user is presented with a form allowing them to enter their details,
    and upon successful submission, a new user account is created and the user
    is redirected to the login page.

    If the user is already authenticated, they will be redirected to the task
    list page instead of seeing the registration form.

    Attributes:
    - form_class (Form): The form class used for user registration.
    - success_url (str): The URL to redirect to upon successful registration.
    - template_name (str): The name of the HTML template to use for rendering
      the registration form.

    Methods:
    - dispatch(request, *args, **kwargs): Overridden method that redirects
      authenticated users to the task list page and passes all other requests
      to the default implementation.
    """
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('auth:login')
    template_name = 'registration/register.html'

    def dispatch(self, request, *args, **kwargs):
        """
        Overridden method that redirects authenticated users to the task list
        """
        if self.request.user.is_authenticated:
            return redirect('todo:tasks-list') 
        return super().dispatch(request, *args, **kwargs)
    

def complete_task(request: HttpRequest, pk: str) -> HttpResponse:
    """
    This function is used to complete or uncomplete a Task object by updating the 'complete' attribute of the Task.
    
    Args:
        - request (HttpRequest): The HTTP request sent to the server.
        - pk (str): The uuid of the Task object to be updated.
        
    Returns:
        - HttpResponse: The HTTP response with a redirect to the tasks-list page.
    """

    # Retrieve the Task object using the pk
    task = get_object_or_404(Task, uuid=pk)

    # Get the 'complete' parameter from the request GET parameters
    complete = request.GET.get('complete')

    # Set the 'complete' attribute of the Task to True or False depending on the 'complete' parameter
    task.complete = True if complete == 'True' else False

    # Save the updated Task object to the database
    task.save()

    # Redirect to the tasks-list page
    return redirect('todo:tasks-list')

templates/todo/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}


    <h1>
        Are you sure you want to delete this task?
    </h1>
    <p><strong>Title: </strong> {{ object.title }}</p>
    <p><strong>due_date: </strong> {{ object.due_date }}</p>
    <p><strong>Complete: </strong> {{ object.complete }}</p>


    <form action="{% url 'todo:task-delete' task.uuid %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes">
        <a href="{% url 'todo:tasks-list' %}" class="btn">No</a>
    </form>



{% endblock %}

templates/todo/task_detail.html
{% extends "base.html" %}
{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div style="width: 350px; margin-left:500px; " class="alert alert-{{ message.tags }} " id="msg" role="alert">
      {{ message }}
   </div>  
    {% endfor %}
</ul>
{% endif %}
Do you want to create a new task? <a href="{% url 'todo:task-create' %}" class="btn">New task</a> <br>
<h1>Task Detail</h1>

<p><strong>Title: </strong> {{ object.title }}</p>
<p><strong>Description: </strong> {{ object.description }}</p>
<p><strong>due_date: </strong> {{ object.due_date }}</p>
<p><strong>Complete: </strong> {{ object.complete }}</p>
<p><strong>Priority: </strong> {{ object.priority }}</p>
<p><strong>created_at at: </strong> {{ object.created_at }}</p>
<p><strong>Updated at: </strong> {{ object.updated_at }}</p>
<p><a href="{% url 'todo:task-update' task.uuid %}" class="btn">Edit</a> 
<a href="{% url 'todo:task-delete' task.uuid %}" class="btn">Delete</a></p>




{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}

{% block content %}


{% if not view.object %}
<h1>Create Task</h1>
{% else %}
<h1>Update Task</h1>
{% endif %}
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  
{% endblock %}

templates/todo/task_list.html
<!-- todo_list/todo_app/templates/todo_app/index.html -->

{% extends "base.html" %}
{% block content %}
<!--index.html-->
{% if object_list %}
<h3>All my lists</h3>
{% endif %}




{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<a href="{% url 'todo:task-create' %}" class="btn">New task</a> <br>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Completed</th>
            <th>Priority</th>
            <th>due_date Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for task in object_list %}
        <tr>
            <td><a href="{% url 'todo:task-detail' task.uuid %}">{{ task.title }}</a></td>
            <td><input type="checkbox" {% if task.complete %}checked{% endif %} id="{{ task.uuid }}"></td>
            <td>{{ task.priority }}</td>
            <td>{{ task.due_date }}</td>
            <td>
                <a href="{% url 'todo:task-detail' task.uuid %}">Detail</a> |
                <a href="{% url 'todo:task-update' task.uuid %}">Update</a> |
                <a href="{% url 'todo:task-delete' task.uuid %}">Delete</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">You have no lists!</td>
        </tr>
        {% endfor %}
    </tbody>
</table>




{% if is_paginated %}
  <nav class="pagination">
    <ul>
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">previous</a></li>
      {% else %}
        <li class="disabled"><span>previous</span></li>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <li class="active"><span>{{ num }}</span></li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li><a href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">next</a></li>
      {% else %}
        <li class="disabled"><span>next</span></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

<script>
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        checkboxes[i].addEventListener('change', function() {
            var url = '/task/' + this.id + '/complete/';
            var xhr = new XMLHttpRequest();
            if (this.checked) {
                // send an extra parameter of True to the server
                xhr.open('GET', url + '?complete=True', true);
                xhr.send();

            } else {
                // send an extra parameter of False to the server
                xhr.open('GET', url + '?complete=False', true);
                xhr.send();
            }
        });
    }
</script>

{% endblock %}